export const SET_POKEMONS_REQUEST = "SET_POKEMONS_REQUEST";
export const SET_POKEMONS_SUCCESS = "SET_POKEMONS_SUCCESS";
export const SET_POKEMONS_FAIL = "SET_POKEMONS_FAIL";

export const POKEMONS_LIST_REQUEST = "POKEMONS_LIST_REQUEST";
export const POKEMONS_LIST_SUCCESS = "POKEMONS_LIST_SUCCESS";
export const POKEMONS_LIST_FAIL = "POKEMONS_LIST_FAIL";

export const POKEMON_CREATED_REQUEST = "POKEMONS_CREATED_REQUEST";
export const POKEMON_CREATED_SUCCESS = "POKEMONS_CREATED_SUCCESS";
export const POKEMON_CREATED_FAIL = "POKEMONS_CREATED_FAIL";

export const POKEMON_DETAILS_REQUEST = "POKEMONS_DETAILS_REQUEST";
export const POKEMON_DETAILS_SUCCESS = "POKEMONS_DETAILS_SUCCESS";
export const POKEMON_DETAILS_FAIL = "POKEMONS_DETAILS_FAIL";

export const POKEMONS_SEARCH = "POKEMONS_SEARCH";

export const FILTER_TYPE = "FILTER_TYPE";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SORT = "SORT";
