const ActionTypes = {
  SET_POKEMONS_REQUEST: "SET_POKEMONS_REQUEST",
  SET_POKEMONS_SUCCESS: "SET_POKEMONS_SUCCESS",
  SET_POKEMONS_FAIL: "SET_POKEMONS_FAIL",

  SET_TYPES_REQUEST: "SET_TYPES_REQUEST",
  SET_TYPES_SUCCESS: "SET_TYPES_SUCCESS",
  SET_TYPES_FAIL: "SET_TYPES_FAIL",

  POKEMON_CREATED_REQUEST: "POKEMONS_CREATED_REQUEST",
  POKEMON_CREATED_SUCCESS: "POKEMONS_CREATED_SUCCESS",
  POKEMON_CREATED_FAIL: "POKEMONS_CREATED_FAIL",

  POKEMON_DETAILS_REQUEST: "POKEMONS_DETAILS_REQUEST",
  POKEMON_DETAILS_SUCCESS: "POKEMONS_DETAILS_SUCCESS",
  POKEMON_DETAILS_FAIL: "POKEMONS_DETAILS_FAIL",

  POKEMONS_SEARCH: "POKEMONS_SEARCH",

  FILTER_TYPE: "FILTER_TYPE",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  SORT: "SORT",
};

export default ActionTypes;
